# Attention Mechanism

In [33]:
import torch
inputs = torch.tensor(
    [[0.43, 0.15, 0.89], # Your (x^1)
    [0.55, 0.87, 0.66], # journey (x^2)
    [0.57, 0.85, 0.64], # starts (x^3)
    [0.22, 0.58, 0.33], # with (x^4)
    [0.77, 0.25, 0.10], # one (x^5)
    [0.05, 0.80, 0.55]] # step (x^6)
)

Computing attention scores

In [34]:
query = inputs[1]                               # python indexing starts with 0
attn_scores_2 = torch.empty(inputs.shape[0])    # an empty tensor array to store attention score values
for i, x_i in enumerate(inputs):
    attn_scores_2[i] = torch.dot(x_i, query)    # dot product of each tensor with query
print(attn_scores_2)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


In [35]:
print(attn_scores_2.sum())

tensor(6.5617)


Normalizing the attention scores

In [9]:
attn_scores_2_sum = attn_scores_2.sum()
attn_weights_2 = torch.empty(inputs.shape[0])
for idx, attn_score in enumerate(attn_scores_2):
    attn_weights_2[idx] = attn_score/attn_scores_2_sum

print(attn_weights_2)
print(attn_weights_2.sum())

tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])
tensor(1.0000)


Applying softmax

In [36]:
attn_weights_2_softmax = torch.softmax(attn_scores_2, dim=-1)
print(attn_weights_2_softmax)
print(attn_weights_2_softmax.sum())

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
tensor(1.)
